//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace performance_tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComponentDetail()
        {
            this.OperationDetails = new HashSet<OperationDetail>();
        }
    
        public int CompId { get; set; }
        public string CompName { get; set; }
        public string CompDescription { get; set; }
        public Nullable<int> ProjId { get; set; }
        public Nullable<int> ComponetID { get; set; }
    
        public virtual ProjectDetail ProjectDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationDetail> OperationDetails { get; set; }
    }
}
