//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace performance_tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatorDetail
    {
        public int OprtrId { get; set; }
        public string OprtrName { get; set; }
        public string OprtrDescription { get; set; }
    }
}
