//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace performance_tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationDetail
    {
        public int OprtnId { get; set; }
        public Nullable<int> OperationId { get; set; }
        public string OprnName { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> DelayTime { get; set; }
        public Nullable<System.DateTime> CycleTime { get; set; }
        public Nullable<int> CompId { get; set; }
        public string OprnDescription { get; set; }
        public Nullable<int> OprtrId { get; set; }
    
        public virtual ComponentDetail ComponentDetail { get; set; }
        public virtual OperatorDetail OperatorDetail { get; set; }
    }
}
