//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace performance_tracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PerformaneAnalyzerEntities : DbContext
    {
        public PerformaneAnalyzerEntities()
            : base("name=PerformaneAnalyzerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComponentDetail> ComponentDetails { get; set; }
        public virtual DbSet<MachineDetail> MachineDetails { get; set; }
        public virtual DbSet<OperationDetail> OperationDetails { get; set; }
        public virtual DbSet<OperatorDetail> OperatorDetails { get; set; }
        public virtual DbSet<ProjectComponentDetail> ProjectComponentDetails { get; set; }
        public virtual DbSet<ProjectDetail> ProjectDetails { get; set; }
    }
}
