//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace performance_tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectComponentDetail
    {
        public int ProjCompId { get; set; }
        public int Prjid { get; set; }
        public int Cmpid { get; set; }
        public string prjcmpDesc { get; set; }
        public Nullable<int> ComponentId { get; set; }
    
        public virtual ProjectDetail ProjectDetail { get; set; }
    }
}
